/*
 * Copyright (c) 2026 @hanyazou
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#pragma once

#include "main.h"

/*
 * Project / board specific configuration.
 *
 * Hardware-dependent definitions that are not generated by STM32CubeMX.
 * Update this file first when porting to another board or MCU.
 */

/* SPI instance for microSD (SPI mode)
 * - SPI peripheral configuration itself is generated by CubeMX.
 * - This handle must match the SPI instance enabled in CubeMX.
 */
#define SD_SPI_HANDLE hspi1

/* SPI pin definitions for microSD (SPI mode)
 *
 * Pins are shared with GPIO and are switched dynamically between:
 *   - Alternate Function (SPI)
 *   - GPIO / Hi-Z
 *
 * NOTE:
 *   Alternate Function (AF) numbers are not shown in the CubeMX UI.
 *   Refer to HAL_SPI_MspInit() in Core/Src/stm32h5xx_hal_msp.c and
 *   keep these values in sync.
 */
/* SPI SCK */
#define SD_SPI_SCK_Pin GPIO_PIN_5
#define SD_SPI_SCK_GPIO_Port GPIOA
#define SD_SPI_SCK_GPIO_AF GPIO_AF5_SPI1
/* SPI MISO */
#define SD_SPI_MISO_Pin GPIO_PIN_6
#define SD_SPI_MISO_GPIO_Port GPIOA
#define SD_SPI_MISO_GPIO_AF GPIO_AF5_SPI1
/* SPI MOSI */
#define SD_SPI_MOSI_Pin GPIO_PIN_7
#define SD_SPI_MOSI_GPIO_Port GPIOA
#define SD_SPI_MOSI_GPIO_AF GPIO_AF5_SPI1

/* microSD Chip Select (CS)
 * - Software-controlled GPIO (CubeMX-generated pin definition).
 */
#define SD_CS_GPIO_Port SPI_SS_GPIO_Port
#define SD_CS_Pin SPI_SS_Pin
